# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GenBBS.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(473, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 10, 221, 341))
        self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::Panel)
        self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Sunken)
        self.frame.setObjectName("frame")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(50, 69, 111, 211))
        self.frame_2.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_2.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_2.setObjectName("frame_2")
        self.crExistingFile = QtWidgets.QPushButton(self.frame_2)
        self.crExistingFile.setGeometry(QtCore.QRect(0, 120, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(True)
        self.crExistingFile.setFont(font)
        self.crExistingFile.setIconSize(QtCore.QSize(20, 20))
        self.crExistingFile.setObjectName("crExistingFile")
        self.crNewFile = QtWidgets.QPushButton(self.frame_2)
        self.crNewFile.setGeometry(QtCore.QRect(0, 0, 111, 91))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(20)
        font.setBold(True)
        self.crNewFile.setFont(font)
        self.crNewFile.setObjectName("crNewFile")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 473, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.crExistingFile.setText(_translate("MainWindow", "Open \n"
"Existing \n"
"File"))
        self.crNewFile.setText(_translate("MainWindow", "+"))
